services:
    _defaults:
        autoconfigure: true

    terminal42_insert_tags.migration.guests:
        class: Terminal42\InsertTagsBundle\Migration\GuestsMigration
        arguments:
            - "@request_stack"
            - "@security.token_storage"
