services:
    _defaults:
        autoconfigure: true

    terminal42_insert_tags.handler:
        class: Terminal42\InsertTagsBundle\InsertTagHandler
        arguments:
            - "@request_stack"
            - "@security.token_storage"
